name: GitHub Merged Pull Request
description: Checks out the GitHub PR merge ref rather than the branch HEAD
author: https://github.com/tee-md
requirements: []
configuration:
  properties:
    mode:
      type: string
    update_prs:
      type: boolean
    oldest_pr:
      type: integer
  required: []
